# Generated by Django 4.2.2 on 2023-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=250)),
                ('img2', models.ImageField(upload_to='pics')),
                ('desc2', models.TextField()),
            ],
        ),
    ]
